version: "3"
services:
 api:
  build:
   context: ./api
  depends_on:
   - db
  volumes:
   - ./api:/app
  ports:
   - 5000:5000
 db:
  image: sqlite:latest
  volumes:
   - ./db:/data/db
 nginx:
  image: nginx:latest
  ports:
   - 80:80
  volumes:
   - ./nginx.conf:/etc/nginx/nginx.conf